package org.orhuntokdemir.generation;
import org.orhuntokdemir.DB.DbManager;
import java.sql.SQLException;

public class OracleDbInserter implements DataInserter {
    private final DbManager oracleDbManager;
    private final RandomDataGenerator generator;
    private int recordCount;

    public OracleDbInserter(DbManager oracleDbManager) {
        this.oracleDbManager = oracleDbManager;
        this.generator = new RandomDataGenerator();
        this.recordCount = 100;//default value
    }
    @Override
    public void setRecordCount(int count) {
        this.recordCount = count;

    }

    @Override
    public void dropComprehensiveTable() throws SQLException {
        String dropTableSql = "DROP TABLE IF EXISTS test_data CASCADE;";
        oracleDbManager.createTable(dropTableSql);


    }


    @Override
    public void createComprehensiveTable() throws SQLException {
        // Implementation for creating comprehensive table in Oracle DB

        String createTableSQL = "CREATE TABLE IF NOT EXISTS test_data (" +
                "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "col_varchar VARCHAR2(100), " +
                "col_nvarchar2 NVARCHAR2(100), " +
                "col_smallint NUMBER(5), " +
                "tc_kimlik_no CHAR(11) NOT NULL CHECK (REGEXP_LIKE(tc_kimlik_no, '^[0-9]{11}$')), " +
                "col_number_10 NUMBER(10), " +
                "col_numeric NUMBER(10, 2), " +
                "col_float float(16), " +
                "col_long LONG, " +
                "COL_DATE DATE, " +
                "col_timestamp TIMESTAMP, " +
                "col_interval INTERVAL DAY TO SECOND, " +
                "col_rowid ROWID, " +
                "col_urowid UROWID, " +
                "col_char CHAR(10), " +
                "col_nchar NCHAR(10), " +
                "col_clob CLOB, " +
                "col_nclob NCLOB, " +
                "col_blob BLOB, " +
                "col_raw RAW(10), " +
                "col_binary_float BINARY_FLOAT, " +
                "col_binary_double BINARY_DOUBLE, " +
                "col_any_type ANYTYPE, " +
                "col_any_data ANYDATA, " +
                "col_any_data_set ANYDATASET, " +
                "col_xml_type XMLTYPE, " +
                "col_http_uri_type HTTPURITYPE, " +
                "col_xdburi_type XDBURIType, " +
                "col_dburi_type DBURIType, " +
                "col_sdo_geometry SDO_GEOMETRY, " +
                "col_sdo_topo_geometry SDO_TOPO_GEOMETRY, " +
                "col_sdo_georaster SDO_GEORASTER" +
                ")";
        oracleDbManager.createTable(createTableSQL);
    }

    @Override
    public void insertComprehensiveData() throws SQLException {
        insertRandomData(recordCount);
    }

    @Override
    public void createAndInsertComprehensiveData(boolean dropFirst) throws SQLException {if (dropFirst) {
            dropComprehensiveTable();
        }
        createComprehensiveTable();
        insertComprehensiveData();
    }

    private void insertRandomData(int recordCount) throws SQLException {
        String insertSQL = "INSERT INTO test_data (" +
                "col_varchar, col_nvarchar2, col_smallint, tc_kimlik_no, col_number_10, " +
                "col_numeric, col_float, col_long, COL_DATE, col_timestamp, " +
                "col_interval, col_rowid, col_urowid, col_char, col_nchar, " +
                "col_clob, col_nclob, col_blob, col_raw, col_binary_float, " +
                "col_binary_double, col_any_type, col_any_data, col_any_data_set, col_xml_type, " +
                "col_http_uri_type, col_xdburi_type, col_dburi_type, col_sdo_geometry, col_sdo_topo_geometry, " +
                "col_sdo_georaster" +
                ") VALUES (" +
                "?, ?, ?, ?, ?, " + // 1-5
                "?, ?, ?, ?, ?, " + // 6-10
                "TO_DSINTERVAL(?), ?, ?, ?, ?, " + // 11-15 (11 is interval)
                "?, ?, ?, ?, ?, " + // 16-20
                "?, SYS.ANYDATA.ConvertVarchar2(?), ?, ?, XMLTYPE(?), " + // 21-25 (22 is any_type, 23 any_data, 25 is xml)
                "HTTPURITYPE(?), XDBURIType(?), DBURIType(?), ?, ?, " + // 26-30
                "?" + // 31
                ")";
        for(int i = 0; i < recordCount; i++) {
            oracleDbManager.insert(insertSQL,
                    generator.generateVarchar(100),                    // col_varchar (1)
                    generator.generateVarchar(100),                    // col_nvarchar2 (2)
                    generator.generateSmallint(),                      // col_smallint (3)
                    generator.generateFakeTCKN(),                      // tc_kimlik_no (4)
                    generator.generateBigint(),                        // col_number_10 (5)
                    generator.generateNumeric(10, 2),                  // col_numeric (6)
                    generator.generateReal(),                          // col_float (7)
                    generator.generateText(),                          // col_long (8)
                    java.sql.Date.valueOf(generator.generateDate()),   // COL_DATE (9)
                    java.sql.Timestamp.valueOf(generator.generateTimestamp()), // col_timestamp (10)
                    generator.generateInterval(),                      // col_interval (11)
                    generator.generateRowId(),                         // col_rowid (12)
                    generator.generateRowId(),                         // col_urowid (13)
                    generator.generateChar(10),                        // col_char (14)
                    generator.generateChar(10),                        // col_nchar (15)
                    generator.generateText(),                          // col_clob (16)
                    generator.generateText(),                          // col_nclob (17)
                    generator.generateBytea(),                         // col_blob (18)
                    generator.generateBytea(),                         // col_raw (19)
                    generator.generateReal(),                          // col_binary_float (20)
                    generator.generateDouble(),                        // col_binary_double (21)
                    null,                                              // col_any_type (22)
                    generator.generateAnyDataVarchar2(),               // col_any_data (23)
                    null,                                              // col_any_data_set (24)
                    generator.generateXml(),                           // col_xml_type (25)
                    generator.generateHttpUri(),                       // col_http_uri_type (26)
                    generator.generateXdbUri(),                        // col_xdburi_type (27)
                    generator.generateDbUri(),                         // col_dburi_type (28)
                    null,                                              // col_sdo_geometry (29)
                    null,                                              // col_sdo_topo_geometry (30)
                    null                                               // col_sdo_georaster (31)
            );
        }
    }

}
