package org.orhuntokdemir.generation;
import org.orhuntokdemir.DB.DbManager;

import java.sql.PreparedStatement;
import java.sql.SQLException;

public class OracleDbInserter implements DataInserter {
    private final DbManager oracleDbManager;
    private final RandomDataGenerator generator;
    private int recordCount;

    public OracleDbInserter(DbManager oracleDbManager) {
        this.oracleDbManager = oracleDbManager;
        this.generator = new RandomDataGenerator();
        this.recordCount = 100;//default value
    }
    @Override
    public void setRecordCount(int count) {
        this.recordCount = count;

    }

    @Override
    public void dropComprehensiveTable() throws SQLException {
        String dropTableSql = "DROP TABLE IF EXISTS test_data CASCADE;";
        oracleDbManager.createTable(dropTableSql);


    }


    @Override
    public void createComprehensiveTable() throws SQLException {
        // Implementation for creating comprehensive table in Oracle DB

        String createTableSQL = "CREATE TABLE IF NOT EXISTS test_data (" +
                "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "col_varchar VARCHAR2(100), " +
                "col_nvarchar2 NVARCHAR2(100), " +
                "col_smallint NUMBER(5), " +
                "tc_kimlik_no CHAR(11) NOT NULL CHECK (REGEXP_LIKE(tc_kimlik_no, '^[0-9]{11}$')), " +
                "col_number_10 NUMBER(10), " +
                "col_numeric NUMBER(10, 2), " +
                "col_float float(16), " +
                "col_long LONG, " +
                "COL_DATE DATE, " +
                "col_timestamp TIMESTAMP, " +
                "col_interval INTERVAL DAY TO SECOND, " +
                "col_rowid ROWID, " +
                "col_urowid UROWID, " +
                "col_char CHAR(10), " +
                "col_nchar NCHAR(10), " +
                "col_clob CLOB, " +
                "col_nclob NCLOB, " +
                "col_blob BLOB, " +
                "col_raw RAW(10), " +
                "col_binary_float BINARY_FLOAT, " +
                "col_binary_double BINARY_DOUBLE, " +
                "col_any_type ANYTYPE, " +
                "col_any_data ANYDATA, " +
                "col_any_data_set ANYDATASET, " +
                "col_xml_type XMLTYPE, " +
                "col_http_uri_type HTTPURITYPE, " +
                "col_xdburi_type XDBURIType, " +
                "col_dburi_type DBURIType, " +
                "col_sdo_geometry SDO_GEOMETRY, " +
                "col_sdo_topo_geometry SDO_TOPO_GEOMETRY, " +
                "col_sdo_georaster SDO_GEORASTER" +
                ")";
        oracleDbManager.createTable(createTableSQL);
    }

    @Override
    public void insertComprehensiveData() throws SQLException {
        insertRandomData(recordCount);
    }

    @Override
    public void createAndInsertComprehensiveData(boolean dropFirst) throws SQLException {if (dropFirst) {
            dropComprehensiveTable();
        }
        createComprehensiveTable();
        insertComprehensiveData();
    }

    private void insertRandomData(int recordCount) throws SQLException {
        String insertSQL = "INSERT INTO test_data (" +
                "col_varchar, col_nvarchar2, col_smallint, tc_kimlik_no, col_number_10, " +
                "col_numeric, col_float, col_long, COL_DATE, col_timestamp, " +
                "col_interval, col_rowid, col_urowid, col_char, col_nchar, " +
                "col_clob, col_nclob, col_blob, col_raw, col_binary_float, " +
                "col_binary_double" +
                ") VALUES (" +
                "?, ?, ?, ?, ?, " +
                "?, ?, ?, ?, ?, " +
                "TO_DSINTERVAL(?), ?, ?, ?, ?, " +
                "?, ?, ?, ?, ?, " +
                "?" +
                ")";
        for(int i = 0; i < recordCount; i++) {
            oracleDbManager.insert(insertSQL,
                    generator.generateVarchar(100),                    // col_varchar
                    generator.generateVarchar(100),                    // col_nvarchar2
                    generator.generateSmallint(),                      // col_smallint
                    generator.generateFakeTCKN(),                      // tc_kimlik_no
                    generator.generateBigint(),                        // col_number_10
                    generator.generateNumeric(10, 2),                  // col_numeric
                    generator.generateReal(),                          // col_float
                    generator.generateText(),                          // col_long
                    java.sql.Date.valueOf(generator.generateDate()),   // COL_DATE
                    java.sql.Timestamp.valueOf(generator.generateTimestamp()), // col_timestamp
                    generator.generateInterval(),                      // col_interval
                    null,                                              // col_rowid
                    null,                                              // col_urowid
                    generator.generateChar(10),                        // col_char
                    generator.generateChar(10),                        // col_nchar
                    generator.generateText(),                          // col_clob
                    generator.generateText(),                          // col_nclob
                    generator.generateBytea(),                         // col_blob
                    generator.generateBytea(),                         // col_raw
                    generator.generateReal(),                          // col_binary_float
                    generator.generateDouble()                         // col_binary_double
            );
        }
    }

}
